live_config_reload = true
working_directory = "None"

# Default colors
[colors.primary]
background = '#282726'
foreground = '#FFFCF0'
dim_foreground = '#FFFCF0'
bright_foreground = '#FFFCF0'

# Cursor colors
[colors.cursor]
text = '#FFFCF0'
cursor = '#FFFCF0'

# Normal colors
[colors.normal]
black = '#100F0F'
red = '#AF3029'
green = '#66800B'
yellow = '#AD8301'
blue = '#205EA6'
magenta = '#A02F6F'
cyan = '#24837B'
white = '#FFFCF0'

# Bright colors
[colors.bright]
black = '#100F0F'
red = '#D14D41'
green = '#879A39'
yellow = '#D0A215'
blue = '#4385BE'
magenta = '#CE5D97'
cyan = '#3AA99F'
white = '#FFFCF0'

# Dim colors
[colors.dim]
black = '#100F0F'
red = '#AF3029'
green = '#66800B'
yellow = '#AD8301'
blue = '#205EA6'
magenta = '#A02F6F'
cyan = '#24837B'
white = '#FFFCF0'

[cursor]
thickness = 0.15
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "alacritty"

[font]
size = 10

[font.bold]
family = "IBM Plex Mono"
style = "bold"

[font.italic]
family = "IBM Plex Mono"
style = "italic"

[font.normal]
family = "IBM Plex Mono"
style = "regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Down"
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 2

[selection]
save_to_clipboard = false

[shell]
program = "/bin/zsh"

[window]
opacity = 0.98

[window.padding]
x = 0
y = 0
