live_config_reload = true
working_directory = "None"

# Colors (Base16 Default Dark)

# Default colors
[colors.primary]
background = '#181818'
foreground = '#d8d8d8'

[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

# Normal colors
[colors.normal]
black   = '#181818'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'

# Bright colors
[colors.bright]
black   = '#585858'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#f8f8f8'

[cursor]
thickness = 0.15
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "alacritty"

[font]
size = 10

[font.bold]
family = "IBM Plex Mono"
style = "bold"

[font.italic]
family = "IBM Plex Mono"
style = "italic"

[font.normal]
family = "IBM Plex Mono"
style = "regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Down"
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 2

[selection]
save_to_clipboard = false

[shell]
program = "/bin/zsh"

[window]
opacity = 0.98

[window.padding]
x = 0
y = 0
